name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔴 Remove or comment out the test step if no tests exist
      # - name: Run tests
      #   run: |
      #     pytest tests/

      - name: Start FastAPI server (optional)
        run: |
          uvicorn main:app --host 0.0.0.0 --port 3456 &
